# Example configuration for repo_rag.
# Copy or reference this file when running `repo-rag index` or `repo-rag query`
# with the `--config` flag.

[embedding]
backend = "sentence-transformer"
model_name = "sentence-transformers/all-MiniLM-L6-v2"

[indexing]
repo = "."
output = "repo_index"
chunk_size = 500
chunk_overlap = 100
extensions = [
  ".py",
  ".md",
  ".txt",
  ".rst",
]

[indexing.embedding]
# This section overrides [embedding] only for indexing.
# backend = "sentence-transformer"
# model_name = "sentence-transformers/all-MiniLM-L6-v2"

[query]
index = "repo_index"
top_k = 5

[query.embedding]
# This section overrides [embedding] only for querying.
# backend = "openai"
# model_name = "text-embedding-3-small"
